import Navbar from "@/components/Navbar";
import { Line, PageShell, PathToPurchase, SectionLabel } from "@/components/WireframeBits";

const About = () => <PageShell><Navbar />
  <section className="wf-section-roomy"><SectionLabel tag="01 · Hero" name="About" intent="Intent · typographic brand statement. No image." /><h1 className="max-w-3xl text-[46px] font-black uppercase leading-tight tracking-wider md:text-[70px]">Bold and natural at the same time.</h1><Line width="70" className="mt-5" /><Line width="60" /></section>
  <section className="wf-section-roomy"><SectionLabel tag="02 · Origin" /><div className="text-[9px] font-black uppercase tracking-[0.28em] text-muted-foreground">ORIGIN</div><div className="wf-section-intent mt-3">Intent · single statement + heritage image. Aligns with Home S03 but goes deeper.</div><div className="wf-story-grid"><div><Line kind="head" width="90" /><Line kind="head" width="70" /><div className="mt-4"><Line width="90" /><Line width="80" /><Line width="90" /><Line width="60" /></div></div><div className="wf-img min-h-[340px]">Heritage image</div></div></section>
  <section className="wf-section"><SectionLabel tag="03 · Approach" name="How We Build" intent="Intent · in-house / small-batch / full-panel testing positioning. Two-up layout." /><div className="wf-zone-row">{[1,2,3,4].map((n)=><div key={n} className="wf-zone p-6"><Line kind="sub" width="60" /><Line width="90" /><Line width="80" /></div>)}</div></section>
  <section className="wf-section"><SectionLabel tag="04 · People" name="Who We Are" intent="Intent · founders / family-owned signal. Portrait cluster." /><div className="grid gap-3 md:grid-cols-3"><div className="wf-img h-[280px]">Portrait 1</div><div className="wf-img h-[280px]">Portrait 2</div><div className="wf-img h-[280px]">Portrait 3</div></div></section>
  <section className="wf-section bg-tier-30 text-background"><SectionLabel tag="05 · Place" name="American Heartland" intent="Intent · deep purple/green flood with map/geography layer. Distinct from Home S03." /><div className="max-w-[480px]"><Line kind="xl" width="90" className="bg-background/95" /><Line kind="xl" width="70" className="bg-background/95" /><Line width="80" className="mt-4 bg-background/45" /><Line width="60" className="bg-background/45" /></div><div className="mt-6 flex h-[200px] items-center justify-center rounded border border-background/25 bg-background/10 text-[9px] font-bold uppercase tracking-[0.16em] text-background/50">Route 66 map / geography layer</div></section>
  <PathToPurchase tag="06 · Path to Purchase" />
</PageShell>;
export default About;
