import Navbar from "@/components/Navbar";
import { PageShell, PathToPurchase, SectionLabel } from "@/components/WireframeBits";

const About = () => <PageShell><Navbar />
  <section className="site-section"><SectionLabel name="About SUNRISE" /><h1 className="site-heading max-w-4xl">Born in the heart of America.</h1><p className="site-subhead mt-6">SUNRISE is a family-owned beverage company founded along America’s historic Route 66 and built for a new generation of non-alcoholic refreshment.</p></section>
  <section className="site-section bg-card"><div className="story-grid"><div><SectionLabel name="Designed to Deliver" /><h2 className="site-heading">Real flavor. Real effects. Crafted with intention.</h2></div><div className="space-y-5 text-base leading-relaxed text-muted-foreground"><p>With deep roots in multi-state beverage formulation and manufacturing, our team is uniquely positioned to lead the non-alcoholic beverage boom.</p><p>Our beverages are infused with hemp-derived Delta-9 THC, sourced from federally legal hemp. Each can contains a perfectly measured potency, designed to elevate without overwhelming.</p><p>Offering multiple fruit-forward flavors, SUNRISE delivers a fresh, alcohol-free drinking experience that’ll leave you wanting more.</p></div></div></section>
  <section className="site-section"><SectionLabel name="How We Build" /><div className="grid gap-4 md:grid-cols-3">{[["Flavor","Natural fruit ingredients and pure cane sugar create a crisp, mid-calorie profile."],["Consistency","Expertly emulsified hemp extracts support a reliable experience every time."],["Transparency","Certified production facilities and full-panel testing keep every can accountable."]].map(([title,body])=><div key={title} className="product-panel"><h3 className="text-sm font-black uppercase tracking-[0.12em] text-primary">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{body}</p></div>)}</div></section>
  <section className="site-section bg-tier-30 text-background"><SectionLabel name="American Heartland" /><h2 className="site-heading max-w-3xl text-background">A beverage company rooted in a real place.</h2><p className="mt-5 max-w-2xl text-base leading-relaxed text-background/80">Cream warmth, saturated color, disciplined structure, and a product line made to feel confident and grounded.</p></section>
  <PathToPurchase />
</PageShell>;
export default About;
